### PR TITLE
Require redis >=4.2,<4.6

### LINKED ISSUE #63: Support redis 4.5.x?
1. There's a race condition bug with redis <=4.4.3 and <=4.5.3, which was addressed in the next bugfix versions.
2. I'm trying to install litestar 2.0.0alpha3, which depends on redis >=4.4.4 and >=4.5.4 (yeah they explicitly require so to avoid that race condition bug).

### PR DESCRIPTION
**Pull request by lqmanh**
Resolve #63

### CODE REVIEW

**Comment by tobymao** [comment]
this is not correct because redis broke cancel catching in 4.4 look at 

https://github.com/redis/redis-py/pull/2104

**Comment by tobymao** [comment]
this is still open https://github.com/redis/redis-py/issues/2511

**Comment by lqmanh** [comment]
Okay this seems really bad. Guess I have to find some workaround then :(((
Thanks for your quick response 👍🏼

**Comment by kartzke** [comment]
Looks like this PR may fix the issue:  https://github.com/redis/redis-py/pull/2695

It's been hanging for 3 months.  There's been some dialog in the last few days, but it needs the attention of a redis-py maintainer.

**Pull request closed without merging**
