### PR TITLE
Use provided json encoder/decoder for stats & info queries

### PR DESCRIPTION
**Pull request by fadedDexofan**

### CODE REVIEW

**Comment by tobymao** [comment]
i don't think this works, json.loads expects a string but you're going get bytes

**Comment by fadedDexofan** [comment]
> i don't think this works, json.loads expects a string but you're going get bytes

From Python 3.6 arg `s` in json.loads can also be `bytes` and `bytearray`

**Comment by tobymao** [comment]
can you fix the build?

**Comment by fadedDexofan** [comment]
Working on it

**Pull request merged**
