### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by grigi**
* [x] Created initial docs scaffold using [Sphinx](https://www.sphinx-doc.org/) using [Furo](https://pradyunsg.me/furo/) theme and the [Markdown](https://myst-parser.readthedocs.io/) syntax.
* [x] Setup a local autoloading devserver by simply running `make devdocs`
* [x] Setup auto APIdoc parsing
* [x] Setup [RTD](https://saq-py.readthedocs.io/) (saq was already taken, although empty) (Pointing to my branch right now, we should change it to your master branch when this is merged in)

For later:
* Rather do a manual doc structure where the apidocs are in the relevant doc pages instead of separate like now.
* A full first draft of the documentation

### CODE REVIEW

**Review by tobymao — APPROVED** [review]
thanks for this, i'm curious why you're doing it?

**Comment by tobymao** [comment]
let's get this built in and have the full documentation in another PR?

**Comment by grigi** [comment]
> thanks for this, i'm curious why you're doing it?

So... I was the most active maintainer of Tortoise-ORM for about 2 years, and it was really nice taking a project and helping to make it more mature. I basically stopped as I got Covid-19 in early 2020 and couldn't cope with things. Managed to hand it over to long2ice to help Andrey, so I felt it was safe to leave the project. The project is practically unrecognisable right now, but the asyncio ORM landscape changed a lot as well, so it's not quite as unique as it was 5 years ago.

I haven't felt the need to work on an OSS project in quite a while, but here I saw something that is best fit for a current work project, and I want to use this (instead of an incredibly complicated and fragile Celery for example).

So I just... started. :shrug:

**Comment by grigi** [comment]
> let's get this built in and have the full documentation in another PR?

Sure, I see you accepted the invite to the project on RTD, I pointed it back to the master of this repo, but you'd need to setup the webhook so it auto-builds on pushes to master.

**Comment by tobymao** [comment]
> > let's get this built in and have the full documentation in another PR?
> 
> Sure, I see you accepted the invite to the project on RTD, I pointed it back to the master of this repo, but you'd need to setup the webhook so it auto-builds on pushes to master.

can you walk me through how to do that or i can give you permissions?

tobikodata.com/slack

**Comment by grigi** [comment]
I'm not entirely sure anymore either.

There's docs:
https://docs.readthedocs.io/en/stable/guides/setup/git-repo-manual.html
https://docs.readthedocs.io/en/stable/guides/setup/git-repo-automatic.html

The place to manage integrations:
https://readthedocs.org/dashboard/saq-py/integrations/

**Pull request merged**
