### PR TITLE
Unpin redis requirement

### PR DESCRIPTION
**Pull request by sondrelg**
Relates to #67 

Note: I haven't deeply looked into the original reason for why it was pinned; just saw it had been resolved a while back.

### CODE REVIEW

**Comment by sondrelg** [comment]
Looks like there are other things preventing us from using saq on a Redis cluster. Saw a lot of 

```
redis.exceptions.RedisClusterException: transaction is deprecated in cluster mode
``` 

and 
```
redis.exceptions.RedisClusterException: EVALSHA - all keys must map to the same key slot
```

but I suppose the redis dependency might still be possible to unpin :relaxed:

**Comment by tobymao** [comment]
i'll fix it on my end

**Comment by sondrelg** [comment]
Why not make it `<5`?

**Comment by sondrelg** [comment]
Ah cool, that's what you ended up doing. Sweet :relaxed:

**Comment by tobymao** [comment]
we’ll you can use 4.5.4 either…

**Pull request closed without merging**
